#!/usr/bin/perl
# xtype - simulate typing in X
# James Stanley 2012

use X11::GUITest qw(SendKeys);

@ARGV or die "Usage: xtype Hello, world!\nxtype simulates typing in X\n";

SendKeys(join(' ', @ARGV));
